[general]
# import = [ "./themes/gruvbox.toml" ]

[terminal]
# shell = { program = "zellij", args = ["--config", "~/dotfiles/zellij/config.kdl"] }
shell = "zellij"
osc52 = "CopyPaste"

[font]
size = 10
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }

[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.9

[keyboard]
bindings = [
	{ key = "Enter", mods = "Control | Shift", action = "ToggleViMode" },
	{ key = "i", mods = "Control", mode = "Vi", action = "ScrollHalfPageDown" }
]
