import = [ "~/.config/alacritty/themes/gruvbox.toml" ]

[shell]
program = "zellij"
args = ["-l", "welcome"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 10

[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.8

[keyboard]
bindings = [
	{ key = "Enter", mods = "Control | Shift", action = "ToggleViMode" },
	{ key = "i", mods = "Control", mode = "Vi", action = "ScrollHalfPageDown" },
]
